# Generated by Django 5.2.8 on 2025-11-14 03:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de creación del registro', verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Fecha y hora de última actualización', verbose_name='Fecha de actualización')),
                ('is_active', models.BooleanField(default=True, help_text='Indica si el registro está activo', verbose_name='Activo')),
                ('date', models.DateField(help_text='Fecha de la asistencia', verbose_name='Fecha')),
                ('status', models.CharField(choices=[('PRESENT', 'Presente'), ('ABSENT', 'Ausente'), ('LATE', 'Tarde'), ('EXCUSED', 'Excusado')], default='PRESENT', help_text='Estado de asistencia', max_length=10, verbose_name='Estado')),
                ('notes', models.TextField(blank=True, help_text='Notas adicionales sobre la asistencia', verbose_name='Notas')),
            ],
            options={
                'verbose_name': 'Asistencia',
                'verbose_name_plural': 'Asistencias',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de creación del registro', verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Fecha y hora de última actualización', verbose_name='Fecha de actualización')),
                ('is_active', models.BooleanField(default=True, help_text='Indica si el registro está activo', verbose_name='Activo')),
                ('value', models.DecimalField(decimal_places=1, help_text='Valor de la calificación (0.0 - 5.0)', max_digits=3, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)], verbose_name='Calificación')),
                ('grade_type', models.CharField(choices=[('QUIZ', 'Quiz'), ('EXAM', 'Examen'), ('HOMEWORK', 'Tarea'), ('PROJECT', 'Proyecto'), ('PARTICIPATION', 'Participación'), ('FINAL', 'Final')], default='EXAM', help_text='Tipo de evaluación', max_length=50, verbose_name='Tipo de calificación')),
                ('weight', models.DecimalField(decimal_places=2, default=100.0, help_text='Peso porcentual de la calificación', max_digits=5, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)], verbose_name='Peso')),
                ('comments', models.TextField(blank=True, help_text='Comentarios del docente sobre la calificación', verbose_name='Comentarios')),
                ('graded_date', models.DateField(auto_now_add=True, help_text='Fecha en que se asignó la calificación', verbose_name='Fecha de calificación')),
            ],
            options={
                'verbose_name': 'Calificación',
                'verbose_name_plural': 'Calificaciones',
                'ordering': ['-graded_date'],
            },
        ),
    ]
