# Generated by Django 5.2.8 on 2025-11-14 03:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='course',
            field=models.ForeignKey(
                help_text='Curso del registro',
                on_delete=django.db.models.deletion.CASCADE,
                related_name='attendances',
                to='courses.course',
                verbose_name='Curso'),
        ),
    ]
