# Generated by Django 5.2.8 on 2025-11-14 03:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='teacher',
            field=models.ForeignKey(
                limit_choices_to={
                    'role': 'TEACHER'},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='courses_taught',
                to=settings.AUTH_USER_MODEL,
                verbose_name='Docente'),
        ),
        migrations.AddField(
            model_name='courseenrollment',
            name='course',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='enrollments',
                to='courses.course'),
        ),
        migrations.AddField(
            model_name='courseenrollment',
            name='student',
            field=models.ForeignKey(
                limit_choices_to={
                    'role': 'STUDENT'},
                on_delete=django.db.models.deletion.CASCADE,
                related_name='enrollments',
                to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='subject',
            name='course',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='subjects',
                to='courses.course'),
        ),
        migrations.AddField(
            model_name='subject',
            name='teacher',
            field=models.ForeignKey(
                limit_choices_to={
                    'role': 'TEACHER'},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='subjects_taught',
                to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='course',
            unique_together={
                (
                    'code',
                    'academic_year',
                    'semester')},
        ),
        migrations.AlterUniqueTogether(
            name='courseenrollment',
            unique_together={
                (
                    'student',
                    'course')},
        ),
    ]
