# Generated by Django 5.2.8 on 2025-11-18 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_remove_legacy_schedule_classroom'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='coursesession',
            new_name='courses_cou_course__5f28f1_idx',
            old_name='coursesess_course_timeslot_idx',
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='day_of_week',
            field=models.IntegerField(choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miércoles'), (3, 'Jueves'), (4, 'Viernes'), (5, 'Sábado'), (6, 'Domingo')]),
        ),
        migrations.AlterUniqueTogether(
            name='timeslot',
            unique_together={('day_of_week', 'start_time', 'end_time')},
        ),
    ]
