# Generated by Django 5.2.8 on 2025-11-14 03:24

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User', fields=[
                ('id', models.BigAutoField(
                    auto_created=True, primary_key=True, serialize=False, verbose_name='ID')), ('password', models.CharField(
                        max_length=128, verbose_name='password')), ('last_login', models.DateTimeField(
                            blank=True, null=True, verbose_name='last login')), ('is_superuser', models.BooleanField(
                                default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')), ('username', models.CharField(
                                    error_messages={
                                        'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[
                                        django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')), ('first_name', models.CharField(
                                            blank=True, max_length=150, verbose_name='first name')), ('last_name', models.CharField(
                                                blank=True, max_length=150, verbose_name='last name')), ('email', models.EmailField(
                                                    blank=True, max_length=254, verbose_name='email address')), ('is_staff', models.BooleanField(
                                                        default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')), ('is_active', models.BooleanField(
                                                            default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')), ('date_joined', models.DateTimeField(
                                                                default=django.utils.timezone.now, verbose_name='date joined')), ('role', models.CharField(
                                                                    choices=[
                                                                        ('ADMIN', 'Administrador'), ('TEACHER', 'Docente'), ('STUDENT', 'Estudiante')], default='STUDENT', help_text='Rol del usuario en el sistema', max_length=10, verbose_name='Rol')), ('phone', models.CharField(
                                                                            blank=True, help_text='Número de teléfono de contacto', max_length=15, null=True, verbose_name='Teléfono')), ('avatar', models.ImageField(
                                                                                blank=True, help_text='Imagen de perfil del usuario', null=True, upload_to='avatars/', verbose_name='Avatar')), ('date_of_birth', models.DateField(
                                                                                    blank=True, help_text='Fecha de nacimiento del usuario', null=True, verbose_name='Fecha de nacimiento')), ('groups', models.ManyToManyField(
                                                                                        blank=True, help_text='The groups this user belongs to.', related_name='custom_user_set', related_query_name='custom_user', to='auth.group', verbose_name='groups')), ('user_permissions', models.ManyToManyField(
                                                                                            blank=True, help_text='Specific permissions for this user.', related_name='custom_user_set', related_query_name='custom_user', to='auth.permission', verbose_name='user permissions')), ], options={
                                                                                                'verbose_name': 'Usuario', 'verbose_name_plural': 'Usuarios', 'ordering': [
                                                                                                    'last_name', 'first_name'], }, managers=[
                                                                                                        ('objects', django.contrib.auth.models.UserManager()), ], ), migrations.CreateModel(
                                                                                                            name='Profile', fields=[
                                                                                                                ('id', models.BigAutoField(
                                                                                                                    auto_created=True, primary_key=True, serialize=False, verbose_name='ID')), ('created_at', models.DateTimeField(
                                                                                                                        auto_now_add=True, help_text='Fecha y hora de creación del registro', verbose_name='Fecha de creación')), ('updated_at', models.DateTimeField(
                                                                                                                            auto_now=True, help_text='Fecha y hora de última actualización', verbose_name='Fecha de actualización')), ('is_active', models.BooleanField(
                                                                                                                                default=True, help_text='Indica si el registro está activo', verbose_name='Activo')), ('bio', models.TextField(
                                                                                                                                    blank=True, help_text='Biografía o descripción del usuario', verbose_name='Biografía')), ('address', models.CharField(
                                                                                                                                        blank=True, help_text='Dirección de residencia', max_length=255, verbose_name='Dirección')), ('city', models.CharField(
                                                                                                                                            blank=True, help_text='Ciudad de residencia', max_length=100, verbose_name='Ciudad')), ('country', models.CharField(
                                                                                                                                                default='Colombia', help_text='País de residencia', max_length=100, verbose_name='País')), ('user', models.OneToOneField(
                                                                                                                                                    on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')), ], options={
                                                                                                                                                        'verbose_name': 'Perfil', 'verbose_name_plural': 'Perfiles', }, ), migrations.AddIndex(
                                                                                                                                                            model_name='user', index=models.Index(
                                                                                                                                                                fields=['email'], name='users_user_email_6f2530_idx'), ), migrations.AddIndex(
                                                                                                                                                                    model_name='user', index=models.Index(
                                                                                                                                                                        fields=['role'], name='users_user_role_36d76d_idx'), ), ]
