# Generated by Django 5.2.8 on 2025-11-18 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_add_target_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='target_url',
            field=models.CharField(blank=True, default=None, max_length=512, null=True, verbose_name='Target URL'),
        ),
    ]
